### ISSUE TITLE
Monitor object changes without registering a ModelAdmin

### ISSUE THREAD

**Issue by atodorov** [FundersClub/django-papertrail#10]
Is it possible for papertrail to hook into all models and log their changes. I want to have a list of:
user, model class, attrbiute, old_value, new_value, timestamp.

From what I can tell in the docs such integration isn't possible. From what I can figure out of Django's model signals we don't have information about which is the current user who performs the action but we do have info if an object was created/deleted and what fields were up for an update.

**Comment by eranrund** [comment]
You are correct, it's not doable out of the box with django-papertrail since Django does not perform change tracking inside the models.
A possible solution would be to try and do something with django-model-util's [FieldTracker](http://django-model-utils.readthedocs.io/en/latest/utilities.html#field-tracker) and a post-save handler that works on models that have the tracker instantiated.
A much less performant solution but without relying on FieldTracker would be to grab the model from the DB in `pre_save` (e.g. `instance._pre_save_data = instance.__class__.objects.get(pk=instance.pk)`) and then compare against this in `post_save`. The problem, obviously, is introducing an extra query to each save as well as race conditions if the model is being accessed and saved from multiple places at the same time.
